name = "siya-slack-bot"
main = "src/index.ts"
compatibility_date = "2023-04-19"
usage_model = "bundled" # 50ms compute time per request

kv_namespaces = [
  { binding = "SLACK_BOT_TOKENS", id = "7d1d5231038041458ccb2e4ee090aadd", preview_id = "50280399e4d749819549fe0658183c86" }
]
