#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Test seems to be broken with introduction of durable objects
# see: https://github.com/cloudflare/miniflare/issues/417
#lerna run test --parallel --stream
lerna run precommit --concurrency 1 --stream
