name: Deploy Slack Bot

on:
  push:
    branches:
      - main
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Slack Bot
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      PLANET_SCALE_DB_URL: ${{ secrets.PLANET_SCALE_DB_URL }}
      
    steps:
      - uses: actions/checkout@v2
        
      - name: restore cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-restore-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-restore-cache-
          
      - name: install dependencies
        id: install-dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npx prisma generate --data-proxy
          npm run bootstrap
        
      - name: deploy slack bot
        id: deploy-slack-bot
        uses: cloudflare/wrangler-action@2.0.0
        with:
          wranglerVersion: '3.0.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/slack-bot
          command: deploy
          secrets: |
            DATABASE_URL
            SLACK_CLIENT_SECRET
            SLACK_SIGNING_SECRET
            SENTRY_DSN
          preCommands: |
            npx prisma db push --schema=../prisma-data-proxy/prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
