name: Deploy Slack Bot

on:
  push:
    branches:
      - main
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Slack Bot
    steps:
      - uses: actions/checkout@v2
        
      - name: restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: install dependencies and cache
        if: steps.restore-lerna.outputs.cache-hit != 'true'
        run: |
          npm run setup
          npx prisma db push --schema=packages/prisma-data-proxy/prisma/schema.prisma
        
      - name: deploy slack bot
        uses: cloudflare/wrangler-action@2.0.0
        with:
          wranglerVersion: '3.0.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: packages/slack-bot
          command: deploy
          secrets: |
            DATABASE_URL
            SLACK_CLIENT_SECRET
            SLACK_SIGNING_SECRET
            SENTRY_DSN
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          PLANET_SCALE_DB_URL: ${{ secrets.PLANET_SCALE_DB_URL }}
